# **Phase 1 Tasks** 
### **Task 1: Series Fundamentals**

In [201]:
import pandas as pd
price = pd.Series([15.99, 23.50, 8.75, 45.25, 32.99],
index=  ['A001', 'A002', 'A003', 'A004', 'A005'], name= 'Product price')
price.head()

A001    15.99
A002    23.50
A003     8.75
A004    45.25
A005    32.99
Name: Product price, dtype: float64

In [202]:
price.tail(2)

A004    45.25
A005    32.99
Name: Product price, dtype: float64

In [203]:
price.mean()

np.float64(25.296000000000003)

### **Task 2: DataFrame Creation**

In [204]:
book= {'Title': ['Python Basics', 'Data Science', 'Machine Learning', 'Deep Learning'],
'Author': ['John Smith', 'Sarah Lee', 'Mike Brown', 'Anna Wilson'],
'Year': [2020, 2021, 2022, 2023],
'Price': [29.99, 39.99, 49.99, 59.99],
'Stock': [15, 8, 12, 5]}
book_store= pd.DataFrame(book)
book_store.head()

              Title       Author  Year  Price  Stock
0     Python Basics   John Smith  2020  29.99     15
1      Data Science    Sarah Lee  2021  39.99      8
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5

In [205]:
book_store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   4 non-null      object
 1   Author  4 non-null      object
 2   Year    4 non-null      int64
 3   Price   4 non-null      float64
 4   Stock   4 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 292.0+ bytes

In [206]:
book_store.describe()

              Year      Price      Stock
count     4.000000   4.000000   4.000000
mean   2021.500000  44.990000  10.000000
std       1.290994  12.909944   4.396969
min    2020.000000  29.990000   5.000000
25%    2020.750000  37.490000   7.250000
50%    2021.500000  44.990000  10.000000
75%    2022.250000  52.490000  12.750000
max    2023.000000  59.990000  15.000000

In [207]:
book_store.describe(include='all')

                Title      Author         Year      Price      Stock
count               4           4     4.000000   4.000000   4.000000
unique              4           4          NaN        NaN        NaN
top     Python Basics  John Smith          NaN        NaN        NaN
freq                1           1          NaN        NaN        NaN
mean              NaN         NaN  2021.500000  44.990000  10.000000
std               NaN         NaN     1.290994  12.909944   4.396969
min               NaN         NaN  2020.000000  29.990000   5.000000
25%               NaN         NaN  2020.750000  37.490000   7.250000
50%               NaN         NaN  2021.500000  44.990000  10.000000
75%               NaN         NaN  2022.250000  52.490000  12.750000
max               NaN         NaN  2023.000000  59.990000  15.000000

### **Task 3: Data Selection**

In [208]:
book_store[book_store['Year']>2021]

              Title       Author  Year  Price  Stock
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5

In [209]:
book_store[book_store['Stock']<10]

           Title       Author  Year  Price  Stock
1   Data Science    Sarah Lee  2021  39.99      8
3  Deep Learning  Anna Wilson  2023  59.99      5

In [210]:
book_store[['Title','Price']]

              Title  Price
0     Python Basics  29.99
1      Data Science  39.99
2  Machine Learning  49.99
3     Deep Learning  59.99

In [211]:
book_store.loc[0:1,['Title','Author']]

           Title      Author
0  Python Basics  John Smith
1   Data Science   Sarah Lee

In [212]:
book_store.iloc[2:4,0:4]

              Title       Author  Year  Price
2  Machine Learning   Mike Brown  2022  49.99
3     Deep Learning  Anna Wilson  2023  59.99

### **Task 4: File Operations**

In [213]:
book_store.to_csv('book_store.csv',index= False)

In [214]:
book1= {'Title': ['MLops', 'AI Engineering'],
'Author': ['ken Chuks', 'Arinze Paul'],
'Year': [2020, 2021],
'Price': [23.99, 29.99],
'Stock': [11, 18]}
book_store1= pd.DataFrame(book1)
book_store= pd.concat([book_store,book_store1],ignore_index= True)
book_store

              Title       Author  Year  Price  Stock
0     Python Basics   John Smith  2020  29.99     15
1      Data Science    Sarah Lee  2021  39.99      8
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5
4             MLops    ken Chuks  2020  23.99     11
5    AI Engineering  Arinze Paul  2021  29.99     18

### **Task 5: Practice Project - "Student Performance Tracker"**

In [215]:
class_t={
'Name':['ken','paul','bolu','chuka','bola','peter'],
'Math_Score':[12,None,67,32,18,None],
'Science_Score':[92,18,None,47,28,62],
'English_Score':[74,None,76,65,81,71]}
class_track= pd.DataFrame(class_t)
class_track

    Name  Math_Score  Science_Score  English_Score
0    ken        12.0           92.0           74.0
1   paul         NaN           18.0            NaN
2   bolu        67.0            NaN           76.0
3  chuka        32.0           47.0           65.0
4   bola        18.0           28.0           81.0
5  peter         NaN           62.0           71.0

In [216]:
class_track['Name']=class_track['Name'].str.capitalize()
class_track.head()

    Name  Math_Score  Science_Score  English_Score
0    Ken        12.0           92.0           74.0
1   Paul         NaN           18.0            NaN
2   Bolu        67.0            NaN           76.0
3  Chuka        32.0           47.0           65.0
4   Bola        18.0           28.0           81.0

In [217]:
class_track['Avg_Score']= class_track[['Math_Score','Science_Score','English_Score']].mean(axis=1)
class_track.head()

    Name  Math_Score  Science_Score  English_Score  Avg_Score
0    Ken        12.0           92.0           74.0  59.333333
1   Paul         NaN           18.0            NaN  18.000000
2   Bolu        67.0            NaN           76.0  71.500000
3  Chuka        32.0           47.0           65.0  48.000000
4   Bola        18.0           28.0           81.0  42.333333

In [218]:
class_track[class_track['Math_Score']>20]

    Name  Math_Score  Science_Score  English_Score  Avg_Score
2   Bolu        67.0            NaN           76.0       71.5
3  Chuka        32.0           47.0           65.0       48.0

In [219]:
class_track['Total_Score']=class_track[['Math_Score','Science_Score','English_Score']].sum(axis=1)
class_track.sort_values(by='Total_Score',ascending= True)

    Name  Math_Score  Science_Score  English_Score  Avg_Score  Total_Score
1   Paul         NaN           18.0            NaN  18.000000         18.0
4   Bola        18.0           28.0           81.0  42.333333        127.0
5  Peter         NaN           62.0           71.0  66.500000        133.0
2   Bolu        67.0            NaN           76.0  71.500000        143.0
3  Chuka        32.0           47.0           65.0  48.000000        144.0
0    Ken        12.0           92.0           74.0  59.333333        178.0

# **Phase 2 Tasks**

### **Task 1: Data Cleaning**

In [220]:
data = {
    'customer_id': [101, 102, 103, 104, 101, 105],
    'customer name': ['Alice Smith', 'bob jones', 'Carol Wilson', 'DAVID BROWN', 'alice smith', 'Eva Davis'],
    'order_value': [150.0, None, 200.0, 180.5, 150.0, None],
    'city': ['New York', 'london', 'Paris', 'NEW YORK', 'New York', 'berlin']
}
df= pd.DataFrame(data)
df.head()

   customer_id customer name  order_value      city
0          101   Alice Smith        150.0  New York
1          102     bob jones          NaN    london
2          103  Carol Wilson        200.0     Paris
3          104   DAVID BROWN        180.5  NEW YORK
4          101   alice smith        150.0  New York

In [221]:
df['customer_id'].duplicated().sum()

np.int64(1)

In [222]:
df.drop_duplicates(subset= 'customer_id',inplace= True)

In [223]:
df.head()

   customer_id customer name  order_value      city
0          101   Alice Smith        150.0  New York
1          102     bob jones          NaN    london
2          103  Carol Wilson        200.0     Paris
3          104   DAVID BROWN        180.5  NEW YORK
5          105     Eva Davis          NaN    berlin

In [224]:
df.reset_index(inplace= True)

In [225]:
df.head()

   index  customer_id customer name  order_value      city
0      0          101   Alice Smith        150.0  New York
1      1          102     bob jones          NaN    london
2      2          103  Carol Wilson        200.0     Paris
3      3          104   DAVID BROWN        180.5  NEW YORK
4      5          105     Eva Davis          NaN    berlin

In [226]:
df.drop('index',axis=1,inplace= True)

In [227]:
df.isnull().sum()

customer_id      0
customer name    0
order_value      2
city             0
dtype: int64

In [228]:
df.fillna(df['order_value'].mean(),inplace= True)
df.head()

   customer_id customer name  order_value      city
0          101   Alice Smith   150.000000  New York
1          102     bob jones   176.833333    london
2          103  Carol Wilson   200.000000     Paris
3          104   DAVID BROWN   180.500000  NEW YORK
4          105     Eva Davis   176.833333    berlin

In [229]:
df['city'].str.capitalize()

0    New york
1      London
2       Paris
3    New york
4      Berlin
Name: city, dtype: object

In [230]:
df['customer name'].str.title()

0     Alice Smith
1       Bob Jones
2    Carol Wilson
3     David Brown
4       Eva Davis
Name: customer name, dtype: object

In [231]:
df.head()

   customer_id customer name  order_value      city
0          101   Alice Smith   150.000000  New York
1          102     bob jones   176.833333    london
2          103  Carol Wilson   200.000000     Paris
3          104   DAVID BROWN   180.500000  NEW YORK
4          105     Eva Davis   176.833333    berlin

In [232]:
df['customer email']= df['customer name'].str.split().str[0]+'.'+df['customer name'].str.split().str[1]+'@company.com'

In [233]:
df.head()

   customer_id customer name  order_value      city            customer email
0          101   Alice Smith   150.000000  New York   Alice.Smith@company.com
1          102     bob jones   176.833333    london     bob.jones@company.com
2          103  Carol Wilson   200.000000     Paris  Carol.Wilson@company.com
3          104   DAVID BROWN   180.500000  NEW YORK   DAVID.BROWN@company.com
4          105     Eva Davis   176.833333    berlin     Eva.Davis@company.com

### **Task 2: Data Transformation**

In [234]:
def order_category(value):
    if value < 100:
        return 'Low'
    elif value < 200:
        return 'Medium'
    else:
        return 'High'
    
df['order category']= df['order_value'].apply(order_category)
df.head()

,customer_id,customer name,order_value,city,customer email,order category
0,101,Alice Smith,150.000000,New York,Alice.Smith@company.com,Medium
1,102,bob jones,176.833333,london,bob.jones@company.com,Medium
2,103,Carol Wilson,200.000000,Paris,Carol.Wilson@company.com,High
3,104,DAVID BROWN,180.500000,NEW YORK,DAVID.BROWN@company.com,Medium
4,105,Eva Davis,176.833333,berlin,Eva.Davis@company.com,Medium

In [235]:
def country(value):
    if value == 'New York':
        return 'Americas'
    else:
        return 'Europe'
    
df['region']= df['city'].apply(country)
df.head()

,customer_id,customer name,order_value,city,customer email,order category,region
0,101,Alice Smith,150.000000,New York,Alice.Smith@company.com,Medium,Americas
1,102,bob jones,176.833333,london,bob.jones@company.com,Medium,Europe
2,103,Carol Wilson,200.000000,Paris,Carol.Wilson@company.com,High,Europe
3,104,DAVID BROWN,180.500000,NEW YORK,DAVID.BROWN@company.com,Medium,Europe
4,105,Eva Davis,176.833333,berlin,Eva.Davis@company.com,Medium,Europe

In [236]:
df.dtypes

customer_id         int64
customer name      object
order_value       float64
city               object
customer email     object
order category     object
region             object
dtype: object

In [237]:
# Create a DataFrame of product descriptions:
products = pd.DataFrame({
    'product_code': ['A-100', 'B-250-XL', 'C-300-PRO', 'D-150-LITE'],
    'description': ['red widget', 'BLUE GADGET', 'Green Tool premium', 'yellow device basic']})
products.head()

  product_code          description
0        A-100           red widget
1     B-250-XL          BLUE GADGET
2    C-300-PRO   Green Tool premium
3   D-150-LITE  yellow device basic

In [238]:
products['description']= products['description'].str.title()
products.head()

  product_code          description
0        A-100           Red Widget
1     B-250-XL          Blue Gadget
2    C-300-PRO   Green Tool Premium
3   D-150-LITE  Yellow Device Basic

In [239]:
products.columns

Index(['product_code', 'description'], dtype='object')

In [240]:
products['numeric']= products['product_code'].str.extract(r'(\d+)')
products.head()

  product_code          description numeric
0        A-100           Red Widget     100
1     B-250-XL          Blue Gadget     250
2    C-300-PRO   Green Tool Premium     300
3   D-150-LITE  Yellow Device Basic     150

In [241]:
products['size']= products['product_code'].str.split('-').str[2]

In [242]:
products.head()

  product_code          description numeric  size
0        A-100           Red Widget     100   NaN
1     B-250-XL          Blue Gadget     250    XL
2    C-300-PRO   Green Tool Premium     300   PRO
3   D-150-LITE  Yellow Device Basic     150  LITE

In [243]:
products['product_name']= products.apply(lambda x: f'{x['description']}' if pd.isna(x['size'])
                                         else f'{x['description']} {x['size']}',axis= 1)
products.head()

  product_code          description numeric  size              product_name
0        A-100           Red Widget     100   NaN                Red Widget
1     B-250-XL          Blue Gadget     250    XL            Blue Gadget XL
2    C-300-PRO   Green Tool Premium     300   PRO    Green Tool Premium PRO
3   D-150-LITE  Yellow Device Basic     150  LITE  Yellow Device Basic LITE

In [244]:
# You're given an e-commerce dataset with:
orders = pd.DataFrame({
    'order_id': [1001, 1002, 1003, 1004, 1001, 1005],
    'customer_email': ['ALICE@email.com', 'bob@mail.com', 'carol@email.com', 'DAVID@mail.com', 'alice@email.com', None],
    'product': ['laptop', 'mouse', 'keyboard', 'monitor', 'laptop', 'headphones'],
    'price': [999.99, 25.50, 75.00, 299.99, 999.99, 150.00],
    'quantity': [1, 2, 1, 1, 1, None],
    'order_date': ['2023-01-15', '2023-01-15', '2023-01-16', '2023-01-16', '2023-01-15', '2023-01-17']
})
orders.head(10)

   order_id   customer_email     product   price  quantity  order_date
0      1001  ALICE@email.com      laptop  999.99       1.0  2023-01-15
1      1002     bob@mail.com       mouse   25.50       2.0  2023-01-15
2      1003  carol@email.com    keyboard   75.00       1.0  2023-01-16
3      1004   DAVID@mail.com     monitor  299.99       1.0  2023-01-16
4      1001  alice@email.com      laptop  999.99       1.0  2023-01-15
5      1005             None  headphones  150.00       NaN  2023-01-17

In [245]:
orders.columns.str.capitalize()

Index(['Order_id', 'Customer_email', 'Product', 'Price', 'Quantity',
       'Order_date'],
      dtype='object')

In [246]:
orders['customer_email']= orders['customer_email'].str.lower()

In [247]:
orders.head()

   order_id   customer_email   product   price  quantity  order_date
0      1001  alice@email.com    laptop  999.99       1.0  2023-01-15
1      1002     bob@mail.com     mouse   25.50       2.0  2023-01-15
2      1003  carol@email.com  keyboard   75.00       1.0  2023-01-16
3      1004   david@mail.com   monitor  299.99       1.0  2023-01-16
4      1001  alice@email.com    laptop  999.99       1.0  2023-01-15

In [248]:
orders.duplicated().sum()

np.int64(1)

In [249]:
orders.drop_duplicates(inplace= True)

In [250]:
orders.head()

   order_id   customer_email     product   price  quantity  order_date
0      1001  alice@email.com      laptop  999.99       1.0  2023-01-15
1      1002     bob@mail.com       mouse   25.50       2.0  2023-01-15
2      1003  carol@email.com    keyboard   75.00       1.0  2023-01-16
3      1004   david@mail.com     monitor  299.99       1.0  2023-01-16
5      1005             None  headphones  150.00       NaN  2023-01-17

In [251]:
orders.isna().sum()

order_id          0
customer_email    1
product           0
price             0
quantity          1
order_date        0
dtype: int64

In [252]:
orders.dropna(inplace= True)

In [253]:
orders.head()

   order_id   customer_email   product   price  quantity  order_date
0      1001  alice@email.com    laptop  999.99       1.0  2023-01-15
1      1002     bob@mail.com     mouse   25.50       2.0  2023-01-15
2      1003  carol@email.com  keyboard   75.00       1.0  2023-01-16
3      1004   david@mail.com   monitor  299.99       1.0  2023-01-16

In [254]:
orders['total_price']= orders['price']*orders['quantity']

In [255]:
orders.head()

,order_id,customer_email,product,price,quantity,order_date,total_price
0,1001,alice@email.com,laptop,999.99,1.0,2023-01-15,999.99
1,1002,bob@mail.com,mouse,25.50,2.0,2023-01-15,51.00
2,1003,carol@email.com,keyboard,75.00,1.0,2023-01-16,75.00
3,1004,david@mail.com,monitor,299.99,1.0,2023-01-16,299.99

In [256]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [257]:
orders.head()

,order_id,customer_email,product,price,quantity,order_date,total_price
0,1001,alice@email.com,laptop,999.99,1.0,2023-01-15,999.99
1,1002,bob@mail.com,mouse,25.50,2.0,2023-01-15,51.00
2,1003,carol@email.com,keyboard,75.00,1.0,2023-01-16,75.00
3,1004,david@mail.com,monitor,299.99,1.0,2023-01-16,299.99

In [258]:
orders['order_day']= orders['order_date'].dt.day_name()

In [259]:
orders.head()

,order_id,customer_email,product,price,quantity,order_date,total_price,order_day
0,1001,alice@email.com,laptop,999.99,1.0,2023-01-15,999.99,Sunday
1,1002,bob@mail.com,mouse,25.50,2.0,2023-01-15,51.00,Sunday
2,1003,carol@email.com,keyboard,75.00,1.0,2023-01-16,75.00,Monday
3,1004,david@mail.com,monitor,299.99,1.0,2023-01-16,299.99,Monday

In [260]:
orders.to_csv('cleaned_orders.csv',index= False)


# **Phase 3 Tasks**
### **Task 1: Basic GroupBy Operations**|

In [261]:
# Sales data
sales = pd.DataFrame({
    'Region': ['North', 'South', 'North', 'South', 'East', 'West', 'East', 'West'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Salesperson': ['John', 'Jane', 'John', 'Jane', 'Mike', 'Sarah', 'Mike', 'Sarah'],
    'Revenue': [1000, 1200, 800, 900, 1100, 950, 1300, 850],
    'Units': [10, 12, 8, 9, 11, 10, 13, 9]
})
sales.head()

  Region Product Salesperson  Revenue  Units
0  North       A        John     1000     10
1  South       A        Jane     1200     12
2  North       B        John      800      8
3  South       B        Jane      900      9
4   East       A        Mike     1100     11

In [262]:
sales.groupby('Region').size()

Region
East     2
North    2
South    2
West     2
dtype: int64

In [263]:
total= sales.groupby('Region')
print(total.groups)

{'East': [4, 6], 'North': [0, 2], 'South': [1, 3], 'West': [5, 7]}

In [264]:
total_region_revenue = sales.groupby('Region')['Revenue'].sum()
total_region_revenue

Region
East     2400
North    1800
South    2100
West     1800
Name: Revenue, dtype: int64

In [265]:
revenue_by_region = sales.groupby('Region')['Revenue'].agg(['mean','sum','max','std','count'])
revenue_by_region

          mean   sum   max         std  count
Region
East    1200.0  2400  1300  141.421356      2
North    900.0  1800  1000  141.421356      2
South   1050.0  2100  1200  212.132034      2
West     900.0  1800   950   70.710678      2

In [266]:
avg_revenue_by_product= sales.groupby('Product')['Revenue'].mean()
avg_revenue_by_product

Product
A    1150.0
B     875.0
Name: Revenue, dtype: float64

In [267]:
count_of_sales = sales.groupby('Salesperson').count()
count_of_sales

             Region  Product  Revenue  Units
Salesperson
Jane              2        2        2      2
John              2        2        2      2
Mike              2        2        2      2
Sarah             2        2        2      2

In [268]:
sales['Salesperson'].value_counts()

Salesperson
John     2
Jane     2
Mike     2
Sarah    2
Name: count, dtype: int64

In [269]:
max_single_sale= sales.groupby(['Region','Product']).max()
max_single_sale

               Salesperson  Revenue  Units
Region Product
East   A              Mike     1300     13
North  A              John     1000     10
       B              John      800      8
South  A              Jane     1200     12
       B              Jane      900      9
West   B             Sarah      950     10

### **Task 2: Multi-Level Grouping**

In [270]:
sales.groupby(['Region','Product'])[['Revenue','Units']].sum()

                Revenue  Units
Region Product
East   A           2400     24
North  A           1000     10
       B            800      8
South  A           1200     12
       B            900      9
West   B           1800     19

In [271]:
sales.groupby(['Salesperson'])['Revenue'].mean()

Salesperson
Jane     1050.0
John      900.0
Mike     1200.0
Sarah     900.0
Name: Revenue, dtype: float64

In [272]:
sales.groupby('Product').agg(Diff_Sales=('Revenue', lambda x:x.max()-x.min()))

         Diff_Sales
Product
A               300
B               150

In [273]:
sales.groupby(['Region','Product']).agg(Revenue_Count=('Revenue', 'count'),
                                Revenue_mean=('Revenue', 'mean'),
                                Revenue_std=('Revenue', 'std'))

                Revenue_Count  Revenue_mean  Revenue_std
Region Product
East   A                    2        1200.0   141.421356
North  A                    1        1000.0          NaN
       B                    1         800.0          NaN
South  A                    1        1200.0          NaN
       B                    1         900.0          NaN
West   B                    2         900.0    70.710678

### **Task 4: Practice Project - "Sales Summary Dashboard"**

In [274]:
# Given sales data:
sales_data = pd.DataFrame({
    'Month': ['Jan', 'Jan', 'Feb', 'Feb', 'Mar', 'Mar', 'Jan', 'Feb', 'Mar'],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South', 'West', 'West', 'West'],
    'Product': ['Widget', 'Widget', 'Widget', 'Widget', 'Widget', 'Widget', 'Gadget', 'Gadget', 'Gadget'],
    'Revenue': [5000, 7000, 6000, 8000, 5500, 7500, 3000, 4000, 3500],
    'Cost': [3000, 4000, 3500, 4500, 3200, 4200, 1500, 2000, 1800]
})
sales_data.head()

  Month Region Product  Revenue  Cost
0   Jan  North  Widget     5000  3000
1   Jan  South  Widget     7000  4000
2   Feb  North  Widget     6000  3500
3   Feb  South  Widget     8000  4500
4   Mar  North  Widget     5500  3200

In [275]:
sales_data.groupby('Region')['Revenue'].sum()

Region
North    16500
South    22500
West     10500
Name: Revenue, dtype: int64

In [276]:
sales_data.groupby(['Region','Product'])['Revenue'].sum()

Region  Product
North   Widget     16500
South   Widget     22500
West    Gadget     10500
Name: Revenue, dtype: int64

In [277]:
product_revenue = sales_data.groupby(['Region', 'Product'])['Revenue'].sum().reset_index()
product_revenue

  Region Product  Revenue
0  North  Widget    16500
1  South  Widget    22500
2   West  Gadget    10500

In [278]:
# For each region, rank products by revenue descending, then pick top 2
top_2_per_region = (product_revenue
                    .sort_values(['Region', 'Revenue'], ascending=[True, False])
                    .groupby('Region')
                    .head(2))
top_2_per_region

  Region Product  Revenue
0  North  Widget    16500
1  South  Widget    22500
2   West  Gadget    10500

# **Phase 4 Tasks**
### ***Task 1: Concatenation***

In [279]:
# Create three DataFrames with similar structure
df1 = pd.DataFrame({'Product': ['A', 'B'], 'Q1_Sales': [100, 150]})
df2 = pd.DataFrame({'Product': ['C', 'D'], 'Q1_Sales': [200, 180]})
df3 = pd.DataFrame({'Product': ['A', 'B'], 'Q2_Sales': [120, 160]})

df4 = pd.concat([df1,df2],ignore_index = True)
df4.head()

  Product  Q1_Sales
0       A       100
1       B       150
2       C       200
3       D       180

In [280]:
df5 = pd.concat([df1,df3],ignore_index= True)
df5.head()

  Product  Q1_Sales  Q2_Sales
0       A     100.0       NaN
1       B     150.0       NaN
2       A       NaN     120.0
3       B       NaN     160.0

In [ ]:
df6 = pd.merge(df1, df3, on  = 'Product')
df6

  Product  Q1_Sales  Q2_Sales
0       A       100       120
1       B       150       160

In [290]:
df7= pd.merge(df4,df3, on = 'Product', how = 'outer')
df7

  Product  Q1_Sales  Q2_Sales
0       A       100     120.0
1       B       150     160.0
2       C       200       NaN
3       D       180       NaN

In [285]:
# Merge on multiple columns
sales = pd.DataFrame({
    'region': ['North', 'North', 'South'],
    'product': ['A', 'B', 'A'],
    'sales': [100, 200, 150]
})

targets = pd.DataFrame({
    'region': ['North', 'North', 'South'],
    'product': ['A', 'B', 'B'],
    'target': [90, 180, 120]
})

multi_merge = pd.merge(sales, targets,  on=['region', 'product'], how = 'outer')
multi_merge

  region product  sales  target
0  North       A  100.0    90.0
1  North       B  200.0   180.0
2  South       A  150.0     NaN
3  South       B    NaN   120.0

##  **Task 2: Merging Practice**

In [292]:
# Customer and orders data
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'city': ['London', 'Paris', 'Berlin', 'Madrid']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105],
    'customer_id': [1, 2, 1, 5, 3],
    'amount': [150, 200, 100, 300, 250],
    'product': ['Widget', 'Gadget', 'Tool', 'Widget', 'Gadget']
})

customer_orders = pd.merge(customers, orders, on = 'customer_id', how = 'left')
customer_orders

   customer_id     name    city  order_id  amount product
0            1    Alice  London     101.0   150.0  Widget
1            1    Alice  London     103.0   100.0    Tool
2            2      Bob   Paris     102.0   200.0  Gadget
3            3  Charlie  Berlin     105.0   250.0  Gadget
4            4    Diana  Madrid       NaN     NaN     NaN

In [304]:
customer_orders[customer_orders['amount'].isna()]

   customer_id   name    city  order_id  amount product
4            4  Diana  Madrid       NaN     NaN     NaN

In [293]:
costomers_orders1 =pd.merge(customers, orders, on = 'customer_id', how = 'right')
costomers_orders1

   customer_id     name    city  order_id  amount product
0            1    Alice  London       101     150  Widget
1            2      Bob   Paris       102     200  Gadget
2            1    Alice  London       103     100    Tool
3            5      NaN     NaN       104     300  Widget
4            3  Charlie  Berlin       105     250  Gadget

In [294]:
customers_order2 = pd.merge(customers, orders, on ='customer_id', how= 'outer' )
customers_order2

   customer_id     name    city  order_id  amount product
0            1    Alice  London     101.0   150.0  Widget
1            1    Alice  London     103.0   100.0    Tool
2            2      Bob   Paris     102.0   200.0  Gadget
3            3  Charlie  Berlin     105.0   250.0  Gadget
4            4    Diana  Madrid       NaN     NaN     NaN
5            5      NaN     NaN     104.0   300.0  Widget

In [298]:
customers_order2.groupby(['customer_id', 'name'])['amount'].sum()

customer_id  name
1            Alice      250.0
2            Bob        200.0
3            Charlie    250.0
4            Diana        0.0
Name: amount, dtype: float64