## **Task 1: Series Fundamentals**

In [1]:
import pandas as pd
price = pd.Series([15.99, 23.50, 8.75, 45.25, 32.99],
index=  ['A001', 'A002', 'A003', 'A004', 'A005'], name= 'Product price')
price.head()

A001    15.99
A002    23.50
A003     8.75
A004    45.25
A005    32.99
Name: price, dtype: float64

In [ ]:
price.tail(2)

A004    45.25
A005    32.99
Name: price, dtype: float64

In [ ]:
price.mean()

np.float64(25.296000000000003)

## **Task 2: DataFrame Creation**

In [6]:
book= {'Title': ['Python Basics', 'Data Science', 'Machine Learning', 'Deep Learning'],
'Author': ['John Smith', 'Sarah Lee', 'Mike Brown', 'Anna Wilson'],
'Year': [2020, 2021, 2022, 2023],
'Price': [29.99, 39.99, 49.99, 59.99],
'Stock': [15, 8, 12, 5]}
book_store= pd.DataFrame(book)
book_store.head()

              Title       Author  Year  Price  Stock
0     Python Basics   John Smith  2020  29.99     15
1      Data Science    Sarah Lee  2021  39.99      8
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5

In [7]:
book_store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   4 non-null      object
 1   Author  4 non-null      object
 2   Year    4 non-null      int64
 3   Price   4 non-null      float64
 4   Stock   4 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 292.0+ bytes

In [10]:
book_store.describe()

              Year      Price      Stock
count     4.000000   4.000000   4.000000
mean   2021.500000  44.990000  10.000000
std       1.290994  12.909944   4.396969
min    2020.000000  29.990000   5.000000
25%    2020.750000  37.490000   7.250000
50%    2021.500000  44.990000  10.000000
75%    2022.250000  52.490000  12.750000
max    2023.000000  59.990000  15.000000

In [11]:
book_store.describe(include='all')

                Title      Author         Year      Price      Stock
count               4           4     4.000000   4.000000   4.000000
unique              4           4          NaN        NaN        NaN
top     Python Basics  John Smith          NaN        NaN        NaN
freq                1           1          NaN        NaN        NaN
mean              NaN         NaN  2021.500000  44.990000  10.000000
std               NaN         NaN     1.290994  12.909944   4.396969
min               NaN         NaN  2020.000000  29.990000   5.000000
25%               NaN         NaN  2020.750000  37.490000   7.250000
50%               NaN         NaN  2021.500000  44.990000  10.000000
75%               NaN         NaN  2022.250000  52.490000  12.750000
max               NaN         NaN  2023.000000  59.990000  15.000000

In [16]:
book_store[book_store['Year']>2021]

              Title       Author  Year  Price  Stock
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5

In [18]:
book_store[book_store['Stock']<10]

           Title       Author  Year  Price  Stock
1   Data Science    Sarah Lee  2021  39.99      8
3  Deep Learning  Anna Wilson  2023  59.99      5

In [33]:
book_store[['Title','Price']]

              Title  Price
0     Python Basics  29.99
1      Data Science  39.99
2  Machine Learning  49.99
3     Deep Learning  59.99

In [23]:
book_store.loc[0:1,['Title','Author']]

           Title      Author
0  Python Basics  John Smith
1   Data Science   Sarah Lee

In [24]:
book_store.iloc[2:4,0:4]

              Title       Author  Year  Price
2  Machine Learning   Mike Brown  2022  49.99
3     Deep Learning  Anna Wilson  2023  59.99

In [26]:
book_store.to_csv('book_store.csv',index= False)

In [35]:
book1= {'Title': ['MLops', 'AI Engineering'],
'Author': ['ken Chuks', 'Arinze Paul'],
'Year': [2020, 2021],
'Price': [23.99, 29.99],
'Stock': [11, 18]}
book_store1= pd.DataFrame(book1)
book_store= pd.concat([book_store,book_store1],ignore_index= True)
book_store

              Title       Author  Year  Price  Stock
0     Python Basics   John Smith  2020  29.99     15
1      Data Science    Sarah Lee  2021  39.99      8
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5
4             MLops    ken Chuks  2020  23.99     11
5    AI Engineering  Arinze Paul  2021  29.99     18

## **Task 5: Practice Project - "Student Performance Tracker"**

In [53]:
class_t={
'Name':['ken','paul','bolu','chuka','bola','peter'],
'Math_Score':[12,None,67,32,18,None],
'Science_Score':[92,18,None,47,28,62],
'English_Score':[74,None,76,65,81,71]}
class_track= pd.DataFrame(class_t)
class_track

    Name  Math_Score  Science_Score  English_Score
0    ken        12.0           92.0           74.0
1   paul         NaN           18.0            NaN
2   bolu        67.0            NaN           76.0
3  chuka        32.0           47.0           65.0
4   bola        18.0           28.0           81.0
5  peter         NaN           62.0           71.0

In [54]:
class_track['Name']=class_track['Name'].str.capitalize()
class_track.head()

    Name  Math_Score  Science_Score  English_Score
0    Ken        12.0           92.0           74.0
1   Paul         NaN           18.0            NaN
2   Bolu        67.0            NaN           76.0
3  Chuka        32.0           47.0           65.0
4   Bola        18.0           28.0           81.0

In [56]:
class_track['Avg_Score']= class_track[['Math_Score','Science_Score','English_Score']].mean(axis=1)
class_track.head()

    Name  Math_Score  Science_Score  English_Score  Avg_Score
0    Ken        12.0           92.0           74.0  59.333333
1   Paul         NaN           18.0            NaN  18.000000
2   Bolu        67.0            NaN           76.0  71.500000
3  Chuka        32.0           47.0           65.0  48.000000
4   Bola        18.0           28.0           81.0  42.333333

In [57]:
class_track[class_track['Math_Score']>20]

    Name  Math_Score  Science_Score  English_Score  Avg_Score
2   Bolu        67.0            NaN           76.0       71.5
3  Chuka        32.0           47.0           65.0       48.0

In [62]:
class_track['Total_Score']=class_track[['Math_Score','Science_Score','English_Score']].sum(axis=1)
class_track.sort_values(by='Total_Score',ascending= True)

    Name  Math_Score  Science_Score  English_Score  Avg_Score  Total_Score
1   Paul         NaN           18.0            NaN  18.000000         18.0
4   Bola        18.0           28.0           81.0  42.333333        127.0
5  Peter         NaN           62.0           71.0  66.500000        133.0
2   Bolu        67.0            NaN           76.0  71.500000        143.0
3  Chuka        32.0           47.0           65.0  48.000000        144.0
0    Ken        12.0           92.0           74.0  59.333333        178.0