# **Phase 1 Tasks** 
### **Task 1: Series Fundamentals**

In [129]:
import pandas as pd
price = pd.Series([15.99, 23.50, 8.75, 45.25, 32.99],
index=  ['A001', 'A002', 'A003', 'A004', 'A005'], name= 'Product price')
price.head()

A001    15.99
A002    23.50
A003     8.75
A004    45.25
A005    32.99
Name: Product price, dtype: float64

In [130]:
price.tail(2)

A004    45.25
A005    32.99
Name: Product price, dtype: float64

In [131]:
price.mean()

np.float64(25.296000000000003)

### **Task 2: DataFrame Creation**

In [132]:
book= {'Title': ['Python Basics', 'Data Science', 'Machine Learning', 'Deep Learning'],
'Author': ['John Smith', 'Sarah Lee', 'Mike Brown', 'Anna Wilson'],
'Year': [2020, 2021, 2022, 2023],
'Price': [29.99, 39.99, 49.99, 59.99],
'Stock': [15, 8, 12, 5]}
book_store= pd.DataFrame(book)
book_store.head()

              Title       Author  Year  Price  Stock
0     Python Basics   John Smith  2020  29.99     15
1      Data Science    Sarah Lee  2021  39.99      8
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5

In [133]:
book_store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   4 non-null      object
 1   Author  4 non-null      object
 2   Year    4 non-null      int64
 3   Price   4 non-null      float64
 4   Stock   4 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 292.0+ bytes

In [134]:
book_store.describe()

              Year      Price      Stock
count     4.000000   4.000000   4.000000
mean   2021.500000  44.990000  10.000000
std       1.290994  12.909944   4.396969
min    2020.000000  29.990000   5.000000
25%    2020.750000  37.490000   7.250000
50%    2021.500000  44.990000  10.000000
75%    2022.250000  52.490000  12.750000
max    2023.000000  59.990000  15.000000

In [135]:
book_store.describe(include='all')

                Title      Author         Year      Price      Stock
count               4           4     4.000000   4.000000   4.000000
unique              4           4          NaN        NaN        NaN
top     Python Basics  John Smith          NaN        NaN        NaN
freq                1           1          NaN        NaN        NaN
mean              NaN         NaN  2021.500000  44.990000  10.000000
std               NaN         NaN     1.290994  12.909944   4.396969
min               NaN         NaN  2020.000000  29.990000   5.000000
25%               NaN         NaN  2020.750000  37.490000   7.250000
50%               NaN         NaN  2021.500000  44.990000  10.000000
75%               NaN         NaN  2022.250000  52.490000  12.750000
max               NaN         NaN  2023.000000  59.990000  15.000000

### **Task 3: Data Selection**

In [136]:
book_store[book_store['Year']>2021]

              Title       Author  Year  Price  Stock
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5

In [137]:
book_store[book_store['Stock']<10]

           Title       Author  Year  Price  Stock
1   Data Science    Sarah Lee  2021  39.99      8
3  Deep Learning  Anna Wilson  2023  59.99      5

In [138]:
book_store[['Title','Price']]

              Title  Price
0     Python Basics  29.99
1      Data Science  39.99
2  Machine Learning  49.99
3     Deep Learning  59.99

In [139]:
book_store.loc[0:1,['Title','Author']]

           Title      Author
0  Python Basics  John Smith
1   Data Science   Sarah Lee

In [140]:
book_store.iloc[2:4,0:4]

              Title       Author  Year  Price
2  Machine Learning   Mike Brown  2022  49.99
3     Deep Learning  Anna Wilson  2023  59.99

### **Task 4: File Operations**

In [141]:
book_store.to_csv('book_store.csv',index= False)

In [142]:
book1= {'Title': ['MLops', 'AI Engineering'],
'Author': ['ken Chuks', 'Arinze Paul'],
'Year': [2020, 2021],
'Price': [23.99, 29.99],
'Stock': [11, 18]}
book_store1= pd.DataFrame(book1)
book_store= pd.concat([book_store,book_store1],ignore_index= True)
book_store

              Title       Author  Year  Price  Stock
0     Python Basics   John Smith  2020  29.99     15
1      Data Science    Sarah Lee  2021  39.99      8
2  Machine Learning   Mike Brown  2022  49.99     12
3     Deep Learning  Anna Wilson  2023  59.99      5
4             MLops    ken Chuks  2020  23.99     11
5    AI Engineering  Arinze Paul  2021  29.99     18

### **Task 5: Practice Project - "Student Performance Tracker"**

In [143]:
class_t={
'Name':['ken','paul','bolu','chuka','bola','peter'],
'Math_Score':[12,None,67,32,18,None],
'Science_Score':[92,18,None,47,28,62],
'English_Score':[74,None,76,65,81,71]}
class_track= pd.DataFrame(class_t)
class_track

    Name  Math_Score  Science_Score  English_Score
0    ken        12.0           92.0           74.0
1   paul         NaN           18.0            NaN
2   bolu        67.0            NaN           76.0
3  chuka        32.0           47.0           65.0
4   bola        18.0           28.0           81.0
5  peter         NaN           62.0           71.0

In [144]:
class_track['Name']=class_track['Name'].str.capitalize()
class_track.head()

    Name  Math_Score  Science_Score  English_Score
0    Ken        12.0           92.0           74.0
1   Paul         NaN           18.0            NaN
2   Bolu        67.0            NaN           76.0
3  Chuka        32.0           47.0           65.0
4   Bola        18.0           28.0           81.0

In [145]:
class_track['Avg_Score']= class_track[['Math_Score','Science_Score','English_Score']].mean(axis=1)
class_track.head()

    Name  Math_Score  Science_Score  English_Score  Avg_Score
0    Ken        12.0           92.0           74.0  59.333333
1   Paul         NaN           18.0            NaN  18.000000
2   Bolu        67.0            NaN           76.0  71.500000
3  Chuka        32.0           47.0           65.0  48.000000
4   Bola        18.0           28.0           81.0  42.333333

In [146]:
class_track[class_track['Math_Score']>20]

    Name  Math_Score  Science_Score  English_Score  Avg_Score
2   Bolu        67.0            NaN           76.0       71.5
3  Chuka        32.0           47.0           65.0       48.0

In [147]:
class_track['Total_Score']=class_track[['Math_Score','Science_Score','English_Score']].sum(axis=1)
class_track.sort_values(by='Total_Score',ascending= True)

    Name  Math_Score  Science_Score  English_Score  Avg_Score  Total_Score
1   Paul         NaN           18.0            NaN  18.000000         18.0
4   Bola        18.0           28.0           81.0  42.333333        127.0
5  Peter         NaN           62.0           71.0  66.500000        133.0
2   Bolu        67.0            NaN           76.0  71.500000        143.0
3  Chuka        32.0           47.0           65.0  48.000000        144.0
0    Ken        12.0           92.0           74.0  59.333333        178.0

# **Phase 2 Tasks**

### **Task 1: Data Cleaning**

In [148]:
data = {
    'customer_id': [101, 102, 103, 104, 101, 105],
    'customer name': ['Alice Smith', 'bob jones', 'Carol Wilson', 'DAVID BROWN', 'alice smith', 'Eva Davis'],
    'order_value': [150.0, None, 200.0, 180.5, 150.0, None],
    'city': ['New York', 'london', 'Paris', 'NEW YORK', 'New York', 'berlin']
}
df= pd.DataFrame(data)
df.head()

   customer_id customer name  order_value      city
0          101   Alice Smith        150.0  New York
1          102     bob jones          NaN    london
2          103  Carol Wilson        200.0     Paris
3          104   DAVID BROWN        180.5  NEW YORK
4          101   alice smith        150.0  New York

In [149]:
df['customer_id'].duplicated().sum()

np.int64(1)

In [150]:
df.drop_duplicates(subset= 'customer_id',inplace= True)

In [151]:
df.head()

   customer_id customer name  order_value      city
0          101   Alice Smith        150.0  New York
1          102     bob jones          NaN    london
2          103  Carol Wilson        200.0     Paris
3          104   DAVID BROWN        180.5  NEW YORK
5          105     Eva Davis          NaN    berlin

In [152]:
df.reset_index(inplace= True)

In [153]:
df.head()

   index  customer_id customer name  order_value      city
0      0          101   Alice Smith        150.0  New York
1      1          102     bob jones          NaN    london
2      2          103  Carol Wilson        200.0     Paris
3      3          104   DAVID BROWN        180.5  NEW YORK
4      5          105     Eva Davis          NaN    berlin

In [154]:
df.drop('index',axis=1,inplace= True)

In [155]:
df.isnull().sum()

customer_id      0
customer name    0
order_value      2
city             0
dtype: int64

In [156]:
df.fillna(df['order_value'].mean(),inplace= True)
df.head()

   customer_id customer name  order_value      city
0          101   Alice Smith   150.000000  New York
1          102     bob jones   176.833333    london
2          103  Carol Wilson   200.000000     Paris
3          104   DAVID BROWN   180.500000  NEW YORK
4          105     Eva Davis   176.833333    berlin

In [157]:
df['city'].str.capitalize()

0    New york
1      London
2       Paris
3    New york
4      Berlin
Name: city, dtype: object

In [158]:
df['customer name'].str.title()

0     Alice Smith
1       Bob Jones
2    Carol Wilson
3     David Brown
4       Eva Davis
Name: customer name, dtype: object

In [159]:
df.head()

   customer_id customer name  order_value      city
0          101   Alice Smith   150.000000  New York
1          102     bob jones   176.833333    london
2          103  Carol Wilson   200.000000     Paris
3          104   DAVID BROWN   180.500000  NEW YORK
4          105     Eva Davis   176.833333    berlin

In [160]:
df['customer email']= df['customer name'].str.split().str[0]+'.'+df['customer name'].str.split().str[1]+'@company.com'

In [161]:
df.head()

   customer_id customer name  order_value      city            customer email
0          101   Alice Smith   150.000000  New York   Alice.Smith@company.com
1          102     bob jones   176.833333    london     bob.jones@company.com
2          103  Carol Wilson   200.000000     Paris  Carol.Wilson@company.com
3          104   DAVID BROWN   180.500000  NEW YORK   DAVID.BROWN@company.com
4          105     Eva Davis   176.833333    berlin     Eva.Davis@company.com

### **Task 2: Data Transformation**

In [162]:
def order_category(value):
    if value < 100:
        return 'Low'
    elif value < 200:
        return 'Medium'
    else:
        return 'High'
    
df['order category']= df['order_value'].apply(order_category)
df.head()

,customer_id,customer name,order_value,city,customer email,order category
0,101,Alice Smith,150.000000,New York,Alice.Smith@company.com,Medium
1,102,bob jones,176.833333,london,bob.jones@company.com,Medium
2,103,Carol Wilson,200.000000,Paris,Carol.Wilson@company.com,High
3,104,DAVID BROWN,180.500000,NEW YORK,DAVID.BROWN@company.com,Medium
4,105,Eva Davis,176.833333,berlin,Eva.Davis@company.com,Medium

In [163]:
def country(value):
    if value == 'New York':
        return 'Americas'
    else:
        return 'Europe'
    
df['region']= df['city'].apply(country)
df.head()

,customer_id,customer name,order_value,city,customer email,order category,region
0,101,Alice Smith,150.000000,New York,Alice.Smith@company.com,Medium,Americas
1,102,bob jones,176.833333,london,bob.jones@company.com,Medium,Europe
2,103,Carol Wilson,200.000000,Paris,Carol.Wilson@company.com,High,Europe
3,104,DAVID BROWN,180.500000,NEW YORK,DAVID.BROWN@company.com,Medium,Europe
4,105,Eva Davis,176.833333,berlin,Eva.Davis@company.com,Medium,Europe